/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "gitee.com/wisecloud/crd/pkg/apis/wise2c.com/v1"
	scheme "gitee.com/wisecloud/crd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TenantsGetter has a method to return a TenantInterface.
// A group's client should implement this interface.
type TenantsGetter interface {
	Tenants() TenantInterface
}

// TenantInterface has methods to work with Tenant resources.
type TenantInterface interface {
	Create(*v1.Tenant) (*v1.Tenant, error)
	Update(*v1.Tenant) (*v1.Tenant, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Tenant, error)
	List(opts metav1.ListOptions) (*v1.TenantList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Tenant, err error)
	TenantExpansion
}

// tenants implements TenantInterface
type tenants struct {
	client rest.Interface
}

// newTenants returns a Tenants
func newTenants(c *Wise2cV1Client) *tenants {
	return &tenants{
		client: c.RESTClient(),
	}
}

// Get takes name of the tenant, and returns the corresponding tenant object, and an error if there is any.
func (c *tenants) Get(name string, options metav1.GetOptions) (result *v1.Tenant, err error) {
	result = &v1.Tenant{}
	err = c.client.Get().
		Resource("tenants").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Tenants that match those selectors.
func (c *tenants) List(opts metav1.ListOptions) (result *v1.TenantList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.TenantList{}
	err = c.client.Get().
		Resource("tenants").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tenants.
func (c *tenants) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("tenants").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a tenant and creates it.  Returns the server's representation of the tenant, and an error, if there is any.
func (c *tenants) Create(tenant *v1.Tenant) (result *v1.Tenant, err error) {
	result = &v1.Tenant{}
	err = c.client.Post().
		Resource("tenants").
		Body(tenant).
		Do().
		Into(result)
	return
}

// Update takes the representation of a tenant and updates it. Returns the server's representation of the tenant, and an error, if there is any.
func (c *tenants) Update(tenant *v1.Tenant) (result *v1.Tenant, err error) {
	result = &v1.Tenant{}
	err = c.client.Put().
		Resource("tenants").
		Name(tenant.Name).
		Body(tenant).
		Do().
		Into(result)
	return
}

// Delete takes name of the tenant and deletes it. Returns an error if one occurs.
func (c *tenants) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("tenants").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tenants) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("tenants").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched tenant.
func (c *tenants) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Tenant, err error) {
	result = &v1.Tenant{}
	err = c.client.Patch(pt).
		Resource("tenants").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
